plugin:
    name: 'maki3000.project::lang.plugin.name'
    description: 'maki3000.project::lang.plugin.description'
    author: maki3000
    icon: oc-icon-copyright
    homepage: ''
permissions:
    project:
        tab: Project
        label: Project
