list: $/maki3000/project/models/color/columns.yaml
modelClass: Maki3000\Project\Models\Color
title: Colors
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'maki3000/project/colors/update/:id'
